### ISSUE TITLE
Rescale the results plot when toggling legend entries

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#407] opened 2020-04-05 11:09 UTC
# 🙋 Feature Request

We can toggle lines on the plot by clicking on legend entries.
Removing and adding lines should also rescale the Y axis.

## 🔦 Context

For example, user may want to switch off the "Log scale" to explore "Cumulative deaths" and "Patients in ICU" lines in more details. However, because "Susceptible", "Recovered" and "Infectious" cases are in numbers that are in orders of magnitude higher, the desired lines are crammed into the bottom and are unreadable.

When disabling lines, the plot should adjust its Y axis scale to fit the largest number actually displayed, excluding the hidden lines.

## Related

 -
 -

**Comment by rneher** [comment] 2020-04-05 21:50
rescaling works for me for the model lines, but not for the case counts. 
![image](https://user-images.githubusercontent.com/8379168/78510789-26ecaa00-7798-11ea-95b6-3ca1facf727f.png)

(unselecting the confirmed cases doesn't zoom more)

**Comment by rneher** [comment] 2020-04-10 12:15
this was addressed in e6fd582195cf9f07d8ae43bffa299bada4594325

**Closed by rneher** 2020-04-10 12:15 UTC
Labels: help wanted, s:ui, t:feat
