### ISSUE TITLE
"Infectious Period" not modeled correctly

### ISSUE THREAD

**Issue by Eisenh** [neherlab/covid19_scenarios#137] opened 2020-03-23 01:26 UTC
# 🐛 Bug Report
The "infectious period" does not seem to operate as expected. Increasing the infectious period reduces the total deaths and infections.
For example, with the default scenario:
infectious period 3 days:
Total death: | 1773
Total severe: | 3967
Peak severe: | 665
Peak critical: | 611

Infectious period 7 days
Total death: | 1309
Total severe: | 3123
Peak severe: | 274
Peak critical: | 289

## 🤔 Expected Behavior
Increasing the infectious period should increase transmission and cases

## 😯 Current Behavior
Increasing the infectious period decreases cases

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by ivan-aksamentov** [comment] 2020-03-23 01:39
@Eisenh  Thanks for the report! I will let @nnoll and @rneher to analyze that.

**Comment by nnoll** [comment] 2020-03-23 01:46
This appears to be a duplicate of Issue #74 and relates to a counter-intuitive but ultimately correct feature of the model: R0 is defined **per case** not per unit time so that increasing the infectious period effectively slows down the epidemic by spreading out the same number of additional infections over a longer period of time. This, in a sense, slows the dynamics and thus ultimately the strain on the hospital.

However, given the confusion this feature causes, I think we could improve our documentation to make this more obvious to users. So I'll leave this open to facilitate discussion on how to improve. Thoughts?

**Comment by ivan-aksamentov** [comment] 2020-03-23 02:28
@nnoll We could alsoo add this remark to the upcoming FAQ page as well as add small paragraphs to the help popups for both R0 and Infectious Period.

**Comment by rneher** [comment] 2020-03-23 08:08
there is a QA in the FAQ branch that isn't merged yet. I'll make a PR. we can always add more QAs later. The popup says this: "Average number of days a person is infectious. Over this time, R0 infections happen on average. Together with the latency time, this defines the serial interval. The longer the serial interval, the slower the outbreak." We can make this a little more explicit.

**Comment by nnoll** [comment] 2020-03-23 16:54
I would be hesitant to change such parameters as these are parameterized in natural clinical/public health variables: i.e. serial interval and R0. Since we have an entry in the upcoming FAQ that explains this effect, I'll close this but we can reopen the discussion if the problem persists.

**Closed by nnoll** 2020-03-23 16:54 UTC
Labels: scope:algorithm, severity:bug
