### ISSUE TITLE
JSON import/export

### ISSUE THREAD

**Issue by dkozar** [neherlab/covid19_scenarios#541] opened 2020-04-14 09:40 UTC
# 🙋 Feature Request

@nnoll suggested the feature in https://github.com/neherlab/covid19_scenarios/pull/490#issuecomment-613061734

## 😯 Describe the feature

Project parameters should be able to be exported as JSON, and then imported back. This should bring back the original state.

I'd like the UX to propose solution for the UI.

## 💻 Examples

We already offer a JSON parameters download as a file. Which means we need to add the upload.

Here's an example of how the JSON import/export is usually implemented (link to the app [here](https://dkozar.github.io/treelogy-demo/?data=~(versions~(~)))):

![Snag_27f37bd7](https://user-images.githubusercontent.com/1078403/79209032-c82fcc00-7e3a-11ea-81c8-e8ba03ea2007.png)

![Snag_27f3c67c](https://user-images.githubusercontent.com/1078403/79209051-d1b93400-7e3a-11ea-9fb9-2be8a7f65a9c.png)

![Snag_27f3fbe4](https://user-images.githubusercontent.com/1078403/79209076-da116f00-7e3a-11ea-9fc4-cedf6e6bf8b0.png)

@nnoll please is this what we want, or we want to build a JSON **file upload**?

## Related

 - https://github.com/neherlab/covid19_scenarios/pull/490#issuecomment-613061734

**Comment by nnoll** [comment] 2020-04-14 17:16
@dkozar I was envisioning a true **file upload** instead of a string dump

**Comment by whiver** [comment] 2020-04-16 09:04
This is related to what @nnoll suggested in my PR #381 too.

**Comment by ivan-aksamentov** [comment] 2020-04-16 17:04
File uploads and downloads are mostly already implemented.

The upload have been sitting here for a long time now (since when we planned custom case counts upload and comparison):

https://github.com/neherlab/covid19_scenarios/blob/master/src/components/Main/Compare/ComparisonModalWithButton.tsx
https://github.com/neherlab/covid19_scenarios/blob/master/src/components/Main/Compare/FileUploadZone.tsx
https://github.com/neherlab/covid19_scenarios/blob/master/src/helpers/readFile.ts

One just needs to implement a cohesive UX around it.

**Comment by shijurodhaz** [comment] 2020-04-20 01:25
Hello, I'm new to open source contributions but was hoping to help out with this issue. I was thinking of implementing the UX as follows:
- Add an IMPORT button below the current EXPORT button
- Display a modal that allows the user to upload a JSON file
- If the file is uploaded and the user clicks DONE, the data gets populated or an error is displayed (if the file is formatted incorrectly)
- The user can also click CANCEL instead to go back to the main screen. 

Does this make sense or am I not understanding the feature correctly? Thank you!

**Comment by ivan-aksamentov** [comment] 2020-04-20 07:18
@shijurodhaz This is correct, yes, with a few additions:

 -  Instead of creating a new modal, we would like to merge this "scenario loader" widget (to replace current scenario dropdown) and to further extend it with the export functionality (issue: #397, PR: #490)
 - The dropzone and file reader are mostly implemented, as pointed out in my comment above

 - As an example data for the upload you can use the following
   - for scenario population, epidemiological, simulation parameters and mitigation table, you can take one of the elements of the array (for one country) in: https://github.com/neherlab/covid19_scenarios/blob/master/src/assets/data/scenarios/scenarios.json
   - for age distribution - the corresponding country's element in this array:
https://github.com/neherlab/covid19_scenarios/blob/master/src/assets/data/country_age_distribution.json
    - for severity table, you can take all of the: https://github.com/neherlab/covid19_scenarios/blob/master/src/assets/data/severityData.json

 - The import feature should create a seamless experience with the corresponding export feature. Note that the export currently does not produce the sufficient data in order to reproduce the results (see the list above). That has to be adjusted.

 - On input and output, data should be serialized/deserialized and validated using JSON-schema-generated types and validators. For example, see how scenarios are loaded from the default json files in `getScenarioData()`: https://github.com/neherlab/covid19_scenarios/blob/master/src/components/Main/state/scenarioData.ts 
  Similarly for other pieces.

 - Serialization and validation errors should be reported to the user. Not necessary to create a UI for that right now, but error handling should be very clearly defined and not just `console.error()` everywhere.

I will review and merge #490 tomorrow. But the UI part is not going to be the hard one. It is mostly about getting all pieces of data correctly in all cases between export and import.

Ideally user should be able to import-export the same data in a loop and not loose any data and not produce any errors, no matter how many loop iterations are there.

**Comment by shijurodhaz** [comment] 2020-04-21 00:39
@ivan-aksamentov Since issue #397 is related to this one and is still open, I could try tackling that one first and maybe return to this later.

**Comment by ivan-aksamentov** [comment] 2020-04-21 01:43
@shijurodhaz The #397 was solved in #490 . Sorry for not making it clear. 
We have only 2 days remaining before the release 1.2, so I think I will take over the import/export feature.

Feel free to explore our other issues if you have time
https://github.com/neherlab/covid19_scenarios/issues

**Comment by shijurodhaz** [comment] 2020-04-21 01:59
Sure, I'll try to check the other issues out. Thank you.

**Comment by whiver** [comment] 2020-04-21 09:01
@ivan-aksamentov I'm modifying FileUploadZone.tsx in #381 for the case count import. I'm adding more features, like the accepted file extensions, error handling and some styling. I think it's mergeable now, even if the UI is not perfect (I can improve it afterwards).

**Comment by ivan-aksamentov** [comment] 2020-04-21 20:54
@whiver Thanks. We did not plan to merge it before we release 1.2. I guess we can resolve any conflicts afterwards.

**Comment by ivan-aksamentov** [comment] 2020-05-06 22:22
Resolved in #635

**Closed** 2020-05-06 22:23 UTC
Labels: IMPORTANT, help wanted, s:ui, t:feat
