### ISSUE TITLE
Confirmed cases field is not loaded for Populations with spaces in their names ?

### ISSUE THREAD

**Issue by jc92** [neherlab/covid19_scenarios#273] opened 2020-03-28 19:07 UTC
# 🐛 Bug Report

When selecting populations with spaces, e.g. CHE-Appenzell Innerrhoden, CHE-St. Gallen,  CHE-Appenzell Ausserrhoden "Confirmed cases" is empty

## How to reproduce
Steps to reproduce the issue:

 1. select CHE-St. Gallen as population.

## 😯 Current Behavior

 Confirmed cases is not loaded and "None" is displayed

## 🤔 Expected Behavior

Confirmed cases with respective Location should be selected.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |  Google Chrome
| Operating System | MacOS
|                  |

## Related

 -

**Comment by ivan-aksamentov** [comment] 2020-03-29 00:04
@jc92 Confirmed. Will investigate ASAP.
Thanks for the report!

**Comment by rcbevans** [comment] 2020-03-29 07:18
Not sure if you got around to looking at this @ivan-aksamentov.

The problem is that spaces in `scenarios.json' are being represented by `\u00a0` which is a no break space, and the spaces in `case_counts.json` are being represented by `\u0020`, which is a  regular space.  Javascript comparison sees the two as different, and so the spinner etc see the property as undefined.

Running a find and replace of `\u00a0` with `\u0020` in `scenarios.json` gets things working again.

Are these json files/scenarios programmatically generated?  (I haven't looked much into the _data repo).

**Comment by rneher** [comment] 2020-03-30 15:29
I see. It works for `USA-New York`. To this probably happens due to a mismatch here:
https://github.com/neherlab/covid19_scenarios_data/blob/master/parsers/switzerland.py#L12
and here:
https://github.com/neherlab/covid19_scenarios_data/blob/master/populationData.tsv#L61
I'll fix in the data repo.

**Comment by rneher** [comment] 2020-03-30 15:49
should be fixed in 
https://github.com/neherlab/covid19_scenarios_data/commit/df9432241e3122fadd60a8997c5289d7f123b0af

**Closed by rneher** 2020-03-30 15:49 UTC
Labels: IMPORTANT, help wanted, s:ui, t:bug
