### ISSUE TITLE
Link to previous scenarios

### ISSUE THREAD

**Issue by nnoll** [neherlab/covid19_scenarios#31] opened 2020-03-18 13:33 UTC
It would be great for people to link to custom configured scenarios via a dynamically generated URL. This would allow people to easily share their results.

**Comment by ivan-aksamentov** [comment] 2020-03-18 18:29
This will either require:

  * encoding the entire scenario state in URL params

  * a backend to store the results (which is not impossible with the community efforts)

Similar alternative solution is "import". In this case users can share the param file and/or results file(s).

Related:
 - https://github.com/neherlab/covid19_scenarios/issues/11

**Comment by brunorzn** [comment] 2020-03-20 00:49
I had a look at the "encoding URL" option, which is totally doable.

It will require some work on the "initial state" part, but nothing too complicated though.
The URL will be a bit long, but is it a problem ?
(see  http://graphql.org/swapi-graphql?query=%7B%0A%20%20allVehicles%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20vehicleClass%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A for an example)

The fastest and not most optimised way to do so would probably be to serialise all parameters as JSON and encode them in the URL. 

The main drawback I see with this approach is that it won't necessary be retro-compatible (a URL saved 2 weeks ago probably won't work if breaking changes have been made).
But again, is it really an issue ?

I suggest to take this approach, and see if we do need a backend after all (in that case, we will still have the required "init state" part from above done).

What do you think ?

**Comment by nnoll** [comment] 2020-03-20 00:57
Regarding the reto-compatibilty I don't think this is a concern of huge importance -- the ability for people to share results now would take precedence over the ability to reference results from two weeks ago. The import/export parameters of Issue #11 could solve this use case.

**Comment by brunorzn** [comment] 2020-03-20 02:18
#53

**Comment by ivan-aksamentov** [comment] 2020-03-22 01:24
@brunorzn Looks like it works! :)

I merged #53, but I noticed that it does not restore the names of the scenarios (in dropdowns in card headers). That needs to be fixed, I think.

Additionally, we are using `connected-react-router`, and I think bypassing it may break it. Or at least all the places that rely or will be relying on it will not receive the updated state.
Also, router should parse params for you, if you'd be willing to trasition from urlencoded JSON to proper URL params (e.g.`?param=value&param2=value`)

Let me know if you'd like to work on a followup.

**Comment by brunorzn** [comment] 2020-03-22 02:31
@ivan-aksamentov 

cool for the merge :)

you're right, as mentioned in the PR : 

* it's simply a _quick and dirty_ serialiser - I didn't want to break / refacto anything from the codebase before knowing it better - and I think this feature needs to be shipped quickly

* it does restore the name of the scenarios, when it is not set to "custom" ; it does not restore the "custom" names in the drop down (which are set whenever you change anything), but when you keep the original scenario/population/epidemiology/mitigation, they do appear correctly. Is it really an issue at this point ?

* it could have been done in a redux middleware, with some refactoring

It's true, we bypass the _connected-react-router_, and using _history_ to update the url with a stringified JSON is certainly not the best/most optimised option here. In our case, I don't think what could be broken though, but again I don't know the codebase at all : do you have anything in mind ? I've tried to play around a little bit, moved from page to page, and it seemed ok.

Nevertheless, I agree with you : we should indeed aim for a better option. But I think we should discuss our best options here, because they will probably need some refactoring, at least at some point.

My point is : check that nothing is broken, merge and deploy, so people can quickly copy/paste URLs... but we keep in mind that is technical debt.

What do you think ?

ps: again, I'm just discovering this project, so I'd love to discuss technical choices / roadmap etc with you and the team before I go in a wrong direction ;)

**Comment by jsmith** [comment] 2020-03-22 21:31
Hi @brunorzn, hopefully you don't mind me jumping in on this! I'm a very big fan of [io-ts](https://github.com/gcanti/io-ts) for serializing/deserializing data to/from JSON. Serializing isn't as big of deal but this would certainly be useful for the deserialization of the JSON encoded in the URL.

The code would look something like this:
```typescript
import * as t from 'io-ts'
import { either } from 'fp-ts/lib/Either'

const PopulationDataType = t.type({
  populationServed: t.number,
  country: t.string,
  suspectedCasesToday: t.number,
  importsPerDay: t.number,
  hospitalBeds: t.number,
  ICUBeds: t.number,
  cases: t.string,
})

const EpidemiologicalDataType = t.type({
  r0: t.number,
  incubationTime: t.number,
  infectiousPeriod: t.number,
  lengthHospitalStay: t.number,
  lengthICUStay: t.number,
  seasonalForcing: t.number,
  peakMonth: t.number,
  overflowSeverity: t.number,
})

const DateType = new t.Type<Date, string, unknown>(
  'DateType',
  (u): u is Date => u instanceof Date,
  (u, c) =>
    either.chain(t.string.validate(u, c), s => {
      const d = new Date(s)
      return isNaN(d.getTime()) ? t.failure(u, c) : t.success(d)
    }),
  a => a.toISOString()
)

const DateRangeType = t.type({
  tMin: DateType,
  tMax: DateType,
})

const SimulationData = t.type({
  simulationTimeRange: DateRangeType,
  numberStochasticRuns: t.number,
})

const TimePointType = t.type({
  t: DateType,
  y: t.number,
})

const TimeSeriesType = t.array(TimePointType)

const URLSerializationType = t.type({
  current: {
    overall: t.string,
    population: t.string,
    epidemiological: t.string,
    containment: t.string,
  },
  containment: TimeSeriesType,
  population: PopulationDataType,
  epidemiological: EpidemiologicalDataType,
  simulation: SimulationData,
})
```

Then, you can simply do something like this for deserialization:
```typescript
const result = URLSerializationType.decode(obj) // result is now an error or a decoded object
```

It's a fair amount of additional code; however, it's all statically typed and could be useful for other types of serialization/deserialization. Let me know your thoughts!

**Comment by brunorzn** [comment] 2020-03-22 23:36
I agree with you @jsmith , in theory, but we're talking about adding two dependencies to the codebase, just for the sake of this one deserialisation (which is ugly and not very well typed, but working).

I think I would focus on fixing the existing TS/lint errors first (see `yarn lint`), and consolidating the  codebase before thinking about moving too fast in that `fp-ts` direction.

But that's just my opinion, again I'm not the one who makes the calls here :)

**Comment by jsmith** [comment] 2020-03-23 16:59
Yeah I definitely understand that. Fixing the existing type errors is currently what I'm trying to help out with! One more thing I will point out is that `io-ts` may also be useful in the `processUserResult`function in `src/algorithms/utils/userResult.ts`. This function is currently not implemented but also deals with deserialization (although it is currently deserializing CSV data and not JSON data).

**Comment by ivan-aksamentov** [comment] 2020-03-24 01:03
@brunorzn @jsmith We aren't really constrained with regards to dependencies. Whatever floats your boat. We already have a ton. 

Features and correctness  are more important than bundle size and performance.

Don't forget, our app has quite a different angle compared to  a typical web app. In the realities of an unrolling worldwide tragedy, it's an emergency calculator, that helps to make things done and to make hard decisions. In this regard it is like a dev tool, like VSCode or Eslint, rather than an end-user project like Instagram or Google Calendar.

Experimentation is certainly welcome!

**Comment by jsmith** [comment] 2020-03-25 01:39
@ivan-aksamentov @brunorzn Ok I may look at experimenting with this and adding `io-ts` as a dependency. I think it would be beneficial to ensure that sharing is done correctly. I think the work I do here may be useful for some of the work you describe in #111 (ie. saving to local storage, server, etc).

For example, if you save a run to local storage and come back later, `io-ts` will deserialize the data from local storage and ensure that the data is in the correct format. The same goes for serialized data in URLs as well. This may not be that necessary if the model parameters are very static; however, I could see this being valuable if you plan to add/remove/change parameters.

**Comment by dkozar** [comment] 2020-03-31 16:59
Great format of sharing the (JSON) data via URL is JSURL (https://github.com/Sage/jsurl).

It makes the URLs much shorter and more robust.

JSON:

``` json
{"name":"John Doe","age":42,"children":["Mary","Bill"]}
```

JSON + URL encoding:

```
%7B%22name%22%3A%22John%20Doe%22%2C%22age%22%3A42%2C%22children%22%3A%5B%22Mary%22%2C%22Bill%22%5D%7D
```

JSURL:

``` jsurl
~(name~'John*20Doe~age~42~children~(~'Mary~'Bill))
```

Backward compatibility could be maintained like this:

```js
export const decodeUrl(url:string):OurDataFormat => {
    let obj: OurDataFormat

    try {
        obj = JSURL.parse(str);
    }
    catch (err) { // not a JSURL format
        try {
            obj = OldUrlParser.parse(str);
        }
        catch (err) { // not a OldUrlParser format
            // etc.
        }
    }

    return obj;
}
```

When the app sees the link in the old format, it would immediately convert it into the latest format and update the browser URL.

More: https://github.com/neherlab/covid19_scenarios/issues/326

**Comment by dkozar** [comment] 2020-03-31 21:37
I implemented the serialization described above.

If someone wants to try it out, here's the branch: https://github.com/dkozar/covid19_scenarios/tree/feat/jsurl

![image](https://user-images.githubusercontent.com/1078403/78077258-f4aa0980-739f-11ea-8212-f680273bf7b9.png)

Newly generated links are in this format (but the old links are also functional): http://localhost:3000/?~(population~(ICUBeds~80~cases~%27CHE-Basel-Stadt~country~%27Switzerland~hospitalBeds~698~importsPerDay~0.1~populationServed~195000~suspectedCasesToday~10)~epidemiological~(infectiousPeriod~3~latencyTime~5~lengthHospitalStay~4~lengthICUStay~16~overflowSeverity~2~peakMonth~0~r0~2~seasonalForcing~0.2)~simulation~(simulationTimeRange~(tMax~1598918400000~tMin~1580428800000)~numberStochasticRuns~0)~containment~(~(y~1~t~1580428800000)~(y~1~t~1582483200000)~(y~0.6068708388814913~t~1584537600000)~(y~1~t~1586592000000)~(y~1~t~1588646400000)~(y~0.8250332889480693~t~1590700800000)~(y~1~t~1592755200000)~(y~0.5966444740346205~t~1594809600000)~(y~1~t~1596864000000)~(y~0.9170705725699069~t~1598918400000))~current~%27Custom)

Note that dates are converted to Epoch (timestamps), which is a more convenient way of persisiting dates.

**Comment by dkozar** [comment] 2020-03-31 21:41
Actually the link generation could be tried out here: https://covid19-scenarios-git-fork-dkozar-feat-jsurl.covid19-scenarios.now.sh/

**Comment by brunorzn** [comment] 2020-03-31 21:52
Nice work.

**Comment by dkozar** [comment] 2020-03-31 21:55
There is some problem with performance though. When I reload the page, the page is stuck. Not sure what's the cause, will debug tomorrow.

**Comment by brunorzn** [comment] 2020-03-31 22:04
Alright. Please don't break everything for the sake of URL lengths ;)

**Comment by jsmith** [comment] 2020-04-01 15:18
Ok finally had time to add `io-ts`! The PR is linked just above this comment :)

Also I think #236 reduced the parameters that are being serialized. If you [look here](https://github.com/neherlab/covid19_scenarios/blob/6b872b22c2366ea97613001d81f4a322b4ca15f7/src/components/Main/state/URLSerializer.ts#L35) you'll see we are only serializing the scenario name, the containment data and the simulation data.

**Comment by brunorzn** [comment] 2020-04-01 15:47
@jsmith I've tested your branch locally and : 

* it's not up-to-date with the master branch

* the feature is broken ; it's not directly linked with your code, because it's also broken on the master branch. For instance, on your branch, try changing the R0 parameter, run the simulation, and refresh the page : the R0 is back to default. Mitigation still seems to be working though.

Can you have a look at it ?

**Comment by jsmith** [comment] 2020-04-01 15:53
Ok I'll sync my branch with master! And yes my branch should reflect what's on master right now. The changes in the PR linked above (236) reduced the parameters that are being serialized which is what you're observing. I can try to fix this my by branch! Thanks for testing :)

**Comment by jsmith** [comment] 2020-04-01 16:54
OK so I put up another PR for this change as I thought it would be best to implement this fix on a separate branch! It's linked above just above.

For this I actually completely refactored `Param.types.ts` to be entirely based off `io-ts` For example:
```typescript
export interface PopulationData {
  populationServed: t.number
  country: string
  suspectedCasesToday: number
  importsPerDay: number
  hospitalBeds: number
  ICUBeds: number
  cases: string
}
```

is now defined like
```typescript
export const PopulationDataType = t.type({
  populationServed: t.number,
  country: t.string,
  suspectedCasesToday: t.number,
  importsPerDay: t.number,
  hospitalBeds: t.number,
  ICUBeds: t.number,
  cases: t.string,
})

export type PopulationData = t.TypeOf<typeof PopulationDataType>
```

I could then define `URLSerializationType` very easily:
```typescript
const URLSerializationType = t.type({
  current: t.string,
  data: ScenarioDataType,
})
```

So now the entire `ScenarioDataType` type is being serialized which includes the population, epidemiological, containment and simulation data. I've tested locally and confirmed that parameters are being restored as expected.

See the deployment [here](https://covid19-scenarios-git-fork-jsmith-fixing-url-serialization.covid19-scenarios.now.sh/).

**Comment by brunorzn** [comment] 2020-04-01 17:41
I opened your linked, selected "Austria" , clicked on "Run", moved R0 to 3, clicked on "Run", refreshed the page : R0 is back to default 4.1. Did I miss something ?

**Comment by dkozar** [comment] 2020-04-01 17:49
Did you try this link?

https://covid19-scenarios-7m2htdubs.now.sh/

Video: https://microsofteur-my.sharepoint.com/:v:/g/personal/dakozar_microsoft_com/EclcJrVxNY5EoS_4vpRacRABZqx0hdEUVJ1209jTn2b09w?e=eOvbV4

**Comment by brunorzn** [comment] 2020-04-01 18:12
@dkozar : seems to work great - could you try updating it with the current master branch ?

note: there are two different people working on the same issue with two distinct solutions 🙃

**Comment by dkozar** [comment] 2020-04-01 18:58
I updated an pushed my change.

Wow! The new design is simply beautiful. 🥇

**Comment by jsmith** [comment] 2020-04-01 19:25
@brunorzn Thanks for the catch! If you ran the model quickly after changing the data, the data we serialized was stale. And true, although the primary goal of both of our changes (introduce `io-ts`, introduce `js-url`) complement each other :)

My new changes actually remove the `current` parameter from serialization. Upon deserialization, we immediately set the `current` value to `Custom`. I think this makes the most sense?

New deployment is [here](https://covid19-scenarios-2b6h3lxeg.now.sh/).

**Comment by brunorzn** [comment] 2020-04-01 19:46
> 
> My new changes actually remove the `current` parameter from serialization. Upon deserialization, we immediately set the `current` value to `Custom`. I think this makes the most sense?
> 
Yes I agree.

Well it seems that we now have two working solutions !

Having both at the same time would be ideal : better type consitency with `io-ts` and shorter urls with `js-url`. The work is done, it's just a merging question :)

How do you want to proceed to do so ?

**Comment by dkozar** [comment] 2020-04-01 20:49
My JSURL PR is ready to be merged: https://github.com/neherlab/covid19_scenarios/pull/329

@jsmith as for the

> My new changes actually remove the current parameter from serialization

I don't think it should be removed, because then, how do you recreate the state of the dropdown?

For instance, you select a value from the dropdown and share the link (no custom changes).

**Comment by jsmith** [comment] 2020-04-01 21:13
@dkozar Hmm I never thought about that but restoring from a url is inherently "custom" IMO. Although the "Scenario" value will restore from a url, it's meaningless as the parameters from the URL will overwrite the defaults from the chosen scenario (this is the current behaviour at least). For this reason, I think defaulting to "Custom" is what logically makes sense. Furthermore, the `state.current` value is actually stale for about a second after modifying a parameter so it's possible to modify a parameter, quickly run the scenario and have, for example, "Austria" set as the `current` value *and* the modified parameter shown in the url. Upon restoration using that URL, you will see the scenario still set to "Austria" and the modified parameter which is not correct.

Also if you want to merge your changes in first I don't mind dealing with the conflicts!

**Comment by dkozar** [comment] 2020-04-01 21:16
Sure, let’s do it. It’s pretty late over here (Ireland) so I wouldn’t be able to deal with conflicts anyway :)

**Comment by dkozar** [comment] 2020-04-01 21:18
I have no write access yet..

**Comment by brunorzn** [comment] 2020-04-01 21:22
Yeah let's do that.

For that stale state, we probably should indicate that within the UI, but that's another issue.

_quick summary_  for @ivan-aksamentov : 

can you merge https://github.com/neherlab/covid19_scenarios/pull/329 from @dkozar ? It uses JSURL, and is fully working.

Then @jsmith will update his PR accordingly, with better typed (de)serialisation.

Thanks !

**Comment by dkozar** [comment] 2020-04-01 21:31
@jsmith as for the;

> Hmm I never thought about that but restoring from a url is inherently "custom" IMO. Although the "Scenario" value will restore from a url, it's meaningless as the parameters from the URL will overwrite the defaults from the chosen scenario (this is the current behaviour at least).

So, you either send just the scenario IDs (so the URL is very short), or Custom + bunch of other params. Depending of if the user choses only the scenario, or fiddles with the params.

**Comment by jsmith** [comment] 2020-04-01 23:22
Yes basically! We would first need to deal with the issue of stale scenario values. Then we could do something like you described. This would be fairly easy as we could use the `getScenarioData` function in `data.ts` to initialize the data. If we do want to make this change, I don't think we should until after I introduce `io-ts` which will make this process completely type safe.

**Comment by rneher** [comment] 2020-04-11 17:04
We now have shareable URLs. there are some improvements that will still be made. But the basic functionality is there.

**Closed by rneher** 2020-04-11 17:04 UTC
Labels: help wanted, s:ui, t:feat, t:talk
